// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jpjtupmnjngmmvlyoupv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpwanR1cG1uam5nbW12bHlvdXB2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMDA5NzcsImV4cCI6MjA2MzU3Njk3N30.P1C4eANSj2xPKUhwvjQy8J-LiC4gRFXHMwLr-fAWtUU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);